# Generated by Django 5.0.6 on 2024-06-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_telegramuser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=25)),
                ('coin', models.IntegerField()),
                ('ticket', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.IntegerField(max_length=19, unique=True),
        ),
    ]
