# Generated by Django 5.0.6 on 2024-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pool_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='click',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
