# Generated by Django 5.0.6 on 2024-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_telegramuser_click_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.TextField()),
                ('ticket_count', models.IntegerField()),
                ('coin_count', models.IntegerField()),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
