# Generated by Django 5.0.6 on 2024-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_balance_alter_history_coin_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='coin',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
